# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/v1/groom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/v1/groom.proto\x12\x05groom\x1a\x1fgoogle/protobuf/timestamp.proto\",\n\x17RoomRegistrationRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\"+\n\x18RoomRegistrationResponse\x12\x0f\n\x07room_id\x18\x01 \x01(\x05\"`\n\tNewsFlash\x12\x32\n\tnews_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x11\n\tnews_item\x18\x02 \x01(\tB\x0c\n\n_news_time\"#\n\x10NewsStreamStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9a\x01\n\x05Groom\x12S\n\x10RoomRegistration\x12\x1e.groom.RoomRegistrationRequest\x1a\x1f.groom.RoomRegistrationResponse\x12<\n\rSendNewsFlash\x12\x10.groom.NewsFlash\x1a\x17.groom.NewsStreamStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.v1.groom_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROOMREGISTRATIONREQUEST']._serialized_start=65
  _globals['_ROOMREGISTRATIONREQUEST']._serialized_end=109
  _globals['_ROOMREGISTRATIONRESPONSE']._serialized_start=111
  _globals['_ROOMREGISTRATIONRESPONSE']._serialized_end=154
  _globals['_NEWSFLASH']._serialized_start=156
  _globals['_NEWSFLASH']._serialized_end=252
  _globals['_NEWSSTREAMSTATUS']._serialized_start=254
  _globals['_NEWSSTREAMSTATUS']._serialized_end=289
  _globals['_GROOM']._serialized_start=292
  _globals['_GROOM']._serialized_end=446
# @@protoc_insertion_point(module_scope)
